/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ThreedLoader {
    'parent': string;
    'scene': string;
  }
}

declare global {


  interface HTMLThreedLoaderElement extends Components.ThreedLoader, HTMLStencilElement {}
  var HTMLThreedLoaderElement: {
    prototype: HTMLThreedLoaderElement;
    new (): HTMLThreedLoaderElement;
  };
  interface HTMLElementTagNameMap {
    'threed-loader': HTMLThreedLoaderElement;
  }
}

declare namespace LocalJSX {
  interface ThreedLoader {
    'parent'?: string;
    'scene'?: string;
  }

  interface IntrinsicElements {
    'threed-loader': ThreedLoader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'threed-loader': LocalJSX.ThreedLoader & JSXBase.HTMLAttributes<HTMLThreedLoaderElement>;
    }
  }
}


